### ISSUE TITLE
NetCDF large file option is ignored for history files

### ISSUE THREAD

**Issue by nichannah** [COSIMA/cice5#22]
CICE has a namelist option to turn on netcdf large file support. This flag is only applied to restarts not to diagnostic output. 

We have been getting this error when writing output: 

ice: Error in nf90_enddef: NetCDF: One or more variable sizes violate format constraints

This error usually happens when the file size is too big for the NetCDF format file type. We hope that by enabling large file support on the diagnostic output this will go away.

**Comment by aidanheerdegen** [comment]
If files are getting that large should we look into adding support for netCDF4 with compression?

**Comment by russfiedler** [comment]
Any reason for not enabling netCDF4 rather than large file support? Kills 2 birds with one stone.

**Comment by russfiedler** [comment]
Great minds thinks alike!

**Comment by nichannah** [comment]
OK, good idea. I'll leave the issue open for that purpose.

**Comment by nichannah** [comment]
The large file support option has been removed and netcdf4 compression is now supported.
