### ISSUE TITLE
Add option to not output static data in history files

### ISSUE THREAD

**Issue by aekiss** [COSIMA/cice5#32]
The grid-related fields below  are static but are included in every output .nc file, wasting a lot of runtime and storage. It would be good to provide a namelist flag which would write this grid data to a separate .nc file once per run, and omit it from all other .nc files. It looks like this would require code changes, e.g. at https://github.com/COSIMA/cice5/blob/1d2a9632ae255f0af1d769c4018dad24581ae4fd/io_netcdf/ice_history_write.F90#L249

```
float TLON(nj, ni) ;
float TLAT(nj, ni) ;
float ULON(nj, ni) ;
float ULAT(nj, ni) ;
float NCAT(nc) ;
float tmask(nj, ni) ;
float blkmask(nj, ni) ;
float tarea(nj, ni) ;
float uarea(nj, ni) ;
float dxt(nj, ni) ;
float dyt(nj, ni) ;
float dxu(nj, ni) ;
float dyu(nj, ni) ;
float HTN(nj, ni) ;
float HTE(nj, ni) ;
float ANGLE(nj, ni) ;
float ANGLET(nj, ni) ;
```

**Comment by russfiedler** [comment]
@aekiss From the look of the code the variables from `tmask` onward are optional  so we only need to write them out once for the run (or maybe in a monthly file). That will save a bit of time but may make the final aggregation a bit trickier.

**Comment by aekiss** [comment]
I've done a test - removing these only saves about 20Mb per file, I guess because they compress well as they are highly repetitive & correlated
```
    ANGLE
    ANGLET
    HTE
    HTN
    blkmask
    dxt
    dxu
    dyt
    dyu
    tmask
```

**Comment by nichannah** [comment]
I am going to close this issue given the small impact that doing this would have. We can always reopen if necessary.
