### ISSUE TITLE
WOMBAT requires 10m winds to be passed in OM mode

### ISSUE THREAD

**Issue by russfiedler** [COSIMA/cice5#36]
This is also required if the new Langmuir mixing parameterisation is required in the OM version. In fully coupled mode the winds are passed but not when running in OM mode.

I'd rather not hard code this as it would break existing existing configs. Using CPP preprocessing (it's in the MOM code as ACCESS_WND) is nasty but I'll probably have to do it for the moment. I'd rather this just get done on the fly via a flag that gets read in somewhere and use the OASIS error codes to test whether it should be passed or not.

**Comment by aekiss** [comment]
@russfiedler is this still an issue now that you've implemented the changes for WOMBAT?

**Comment by russfiedler** [comment]
Once the code is accepted it won't be an issue...

**Comment by aekiss** [comment]
@russfiedler so I guess we can close this now?
